### PR TITLE
Support for Infineon TriCore TC2XX/TC3XX

### PR DESCRIPTION
**Pull request by dgarske**
Using macro `WOLFTPM_INFINEON_TRICORE`.

### CODE REVIEW

**Review by Anthony-Tatowicz — COMMENTED** [review]
Looks good

**Review by tatowicz — APPROVED** [review]

**Comment by dgarske** [comment]
> Looks good

Have you been able to build these sources? I coded this up but wasn't able to try building it. The customer I sent it to seemed to like it, but I never did get any coding feedback.

**Comment by dgarske** [comment]
> > Looks good
> 
> Have you been able to build these sources? I coded this up but wasn't able to try building it. The customer I sent it to seemed to like it, but I never did get any coding feedback.

Do you think this could work for any Infineon Tri-Core (TC2XX or TC3XX)? If so I'll update the macro and notes to expand the coverage.

**Comment by tatowicz** [comment]
> > Looks good
> 
> Have you been able to build these sources? I coded this up but wasn't able to try building it. The customer I sent it to seemed to like it, but I never did get any coding feedback.

Yes, these sources build with Tricore, however to get the full TPM building with tasking takes some extra configuration!

**Comment by tatowicz** [comment]
But yes expand coverage to 3xx

**Review by tatowicz — APPROVED** [review]

**Pull request merged**
